/** Iconos Font Awesome Free (solid) usados en la app. */
export {
  faCamera,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faCircle,
  faClipboardList,
  faClock,
  faDivide,
  faEllipsis,
  faHouse,
  faImage,
  faMoon,
  faPlus,
  faSun,
  faTrashCan,
  faUpRightAndDownLeftFromCenter,
  faUser,
  faUtensils,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
